name: Build and Publish Docker Images to GHCR

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]
        openjdk-version: ["21", "22"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ghcr.io/mantouisyummy/pyandjdk:python-${{ matrix.python-version }}-openjdk-${{ matrix.openjdk-version }}
          build-args: |
            PYTHON_VERSION=${{ matrix.python-version }}-slim
            OPENJDK_VERSION=${{ matrix.openjdk-version }}
